#include <ros/ros.h>
#include <nav_msgs/Path.h>
#include <geometry_msgs/PoseStamped.h>
#include <tf2/LinearMath/Quaternion.h>
#include <tf2/utils.h>

#include <blueboat_navigation/DubinInput.h>

#include "steering_functions/dubins_state_space/dubins_state_space.hpp"
#include "steering_functions/reeds_shepp_state_space/reeds_shepp_state_space.hpp"

#include <cmath>
#include <memory>
#include <string>
#include <vector>

namespace blueboat_navigation
{

/**
 * Combined planner node. Subscribes to a DubinInput (start + end PoseStamped)
 * and publishes a nav_msgs/Path generated by either the Dubins or Reeds-Shepp
 * steering function from hbanzhaf/steering_functions.
 *
 * Selection is controlled by the ~planner_type param ("dubins" or
 * "reeds_shepp"). Reeds-Shepp is always bidirectional; Dubins honors the
 * ~forwards_only param (default true).
 */
class DubinsReedsSheppPlanner
{
public:
  DubinsReedsSheppPlanner()
  {
    ros::NodeHandle nh;
    ros::NodeHandle nhP("~");

    // Shared params
    double turning_radius = nhP.param("turning_radius", 1.0);
    m_kappaMax = 1.0 / turning_radius;
    m_discretization = nhP.param("path_resolution", 0.05);

    // Dubins-only param
    m_forwards = nhP.param("forwards_only", true);

    // Planner selection
    nhP.param<std::string>("planner_type", m_plannerType, std::string("dubins"));

    if (m_plannerType != "dubins" && m_plannerType != "reeds_shepp")
    {
      ROS_WARN("[planner] Unknown planner_type '%s', defaulting to 'dubins'",
               m_plannerType.c_str());
      m_plannerType = "dubins";
    }

    // Build the state spaces up front so we don't re-allocate every callback
    m_dubins   = std::make_shared<steering::Dubins_State_Space>(
                    m_kappaMax, m_discretization, m_forwards);
    m_reedsShepp = std::make_shared<steering::Reeds_Shepp_State_Space>(
                    m_kappaMax, m_discretization);

    m_pathPub  = nh.advertise<nav_msgs::Path>("planned_path", 10);
    m_inputSub = nhP.subscribe("planning_input", 10,
                               &DubinsReedsSheppPlanner::onInput, this);

    ROS_INFO("[planner] type=%s  kappa_max=%.3f (R=%.2f m)  res=%.3f m",
             m_plannerType.c_str(), m_kappaMax, turning_radius,
             m_discretization);
    if (m_plannerType == "dubins")
    {
      ROS_INFO("[planner] dubins forwards_only=%s",
               m_forwards ? "true" : "false");
    }
    else
    {
      ROS_INFO("[planner] reeds_shepp: bidirectional (forward + reverse)");
    }
  }

private:
  void onInput(const blueboat_navigation::DubinInput& msg)
  {
    // Build steering::State from PoseStamped
    steering::State start;
    start.x     = msg.start.pose.position.x;
    start.y     = msg.start.pose.position.y;
    start.theta = tf2::getYaw(msg.start.pose.orientation);
    start.kappa = 0.0;
    start.d     = 0.0;

    steering::State goal;
    goal.x     = msg.end.pose.position.x;
    goal.y     = msg.end.pose.position.y;
    goal.theta = tf2::getYaw(msg.end.pose.orientation);
    goal.kappa = 0.0;
    goal.d     = 0.0;

    // Dispatch to selected steering function
    std::vector<steering::State> states;
    if (m_plannerType == "reeds_shepp")
    {
      states = m_reedsShepp->get_path(start, goal);
    }
    else
    {
      states = m_dubins->get_path(start, goal);
    }

    if (states.empty())
    {
      ROS_WARN("[planner] %s returned empty path", m_plannerType.c_str());
      return;
    }

    // Convert to nav_msgs::Path
    nav_msgs::Path path;
    path.header.stamp    = ros::Time::now();
    path.header.frame_id = msg.start.header.frame_id.empty()
                             ? std::string("map")
                             : msg.start.header.frame_id;

    path.poses.reserve(states.size());
    for (const auto& s : states)
    {
      geometry_msgs::PoseStamped p;
      p.header = path.header;
      p.pose.position.x = s.x;
      p.pose.position.y = s.y;
      p.pose.position.z = 0.0;

      // For Reeds-Shepp, s.d == -1 on reverse segments. We keep the heading
      // as-is (theta is the body orientation); downstream controllers can
      // inspect motion direction by differencing successive positions or by
      // subscribing to a richer message if needed.
      tf2::Quaternion q;
      q.setRPY(0.0, 0.0, s.theta);
      p.pose.orientation.x = q.x();
      p.pose.orientation.y = q.y();
      p.pose.orientation.z = q.z();
      p.pose.orientation.w = q.w();

      path.poses.push_back(p);
    }

    m_pathPub.publish(path);
    ROS_INFO("[planner] %s: published path with %zu poses",
             m_plannerType.c_str(), path.poses.size());
  }

  ros::Publisher  m_pathPub;
  ros::Subscriber m_inputSub;

  std::shared_ptr<steering::Dubins_State_Space>      m_dubins;
  std::shared_ptr<steering::Reeds_Shepp_State_Space> m_reedsShepp;

  double      m_kappaMax;
  double      m_discretization;
  bool        m_forwards;
  std::string m_plannerType;
};

} // namespace blueboat_navigation

int main(int argc, char** argv)
{
  ros::init(argc, argv, "dubins_reeds_shepp_planner");
  blueboat_navigation::DubinsReedsSheppPlanner node;
  ros::spin();
  return 0;
}